<?php

declare(strict_types=1);

namespace App\Livewire\Datatable;

use App\Models\Order;
use Illuminate\Database\Eloquent\Builder;

class OrderDatatable extends Datatable
{
    public string $model = Order::class;

    public bool $showFilters = true;
    public array $relationships = ['customer', 'agent', 'items'];
    public array $autoGeneratedHeaders = [];

    public array $searchableColumns = ['order_number', 'payment_phone', 'notes'];

    public array $filterableColumns = [
        'status' => [
            'pending' => 'Pending',
            'processing' => 'Processing',
            'completed' => 'Completed',
            'cancelled' => 'Cancelled',
            'failed' => 'Failed',
        ],
        'payment_status' => [
            'pending' => 'Pending',
            'processing' => 'Processing',
            'completed' => 'Completed',
            'failed' => 'Failed',
            'refunded' => 'Refunded',
        ],
        'payment_method' => [
            'mobile_money' => 'Mobile Money',
            'cash' => 'Cash',
            'bank_transfer' => 'Bank Transfer',
        ],
    ];

    public array $sortableColumns = [
        'order_number',
        'customer_id',
        'agent_id',
        'total',
        'payment_status',
        'status',
        'created_at',
        'completed_at',
    ];

    public array $bulkActions = [
        'mark_processing' => 'Mark as Processing',
        'mark_completed' => 'Mark as Completed',
        'mark_cancelled' => 'Mark as Cancelled',
        'delete' => 'Delete Selected',
    ];

    public function query(): Builder
    {
        return Order::query()
            ->with(['customer', 'agent', 'items'])
            ->when($this->search, function (Builder $query) {
                $query->where(function (Builder $q) {
                    $q->where('order_number', 'like', '%' . $this->search . '%')
                        ->orWhere('payment_phone', 'like', '%' . $this->search . '%')
                        ->orWhere('notes', 'like', '%' . $this->search . '%')
                        ->orWhereHas('customer', function (Builder $customerQuery) {
                            $customerQuery->where('name', 'like', '%' . $this->search . '%')
                                ->orWhere('phone', 'like', '%' . $this->search . '%');
                        });
                });
            })
            ->when($this->filters['status'] ?? null, function (Builder $query, $status) {
                $query->where('status', $status);
            })
            ->when($this->filters['payment_status'] ?? null, function (Builder $query, $paymentStatus) {
                $query->where('payment_status', $paymentStatus);
            })
            ->when($this->filters['payment_method'] ?? null, function (Builder $query, $paymentMethod) {
                $query->where('payment_method', $paymentMethod);
            })
            ->when($this->filters['date_from'] ?? null, function (Builder $query, $dateFrom) {
                $query->whereDate('created_at', '>=', $dateFrom);
            })
            ->when($this->filters['date_to'] ?? null, function (Builder $query, $dateTo) {
                $query->whereDate('created_at', '<=', $dateTo);
            })
            ->orderBy($this->sort, $this->direction);
    }

    public function getRoutes(): array
    {
        return [
            'index' => 'admin.orders.index',
            'show' => 'admin.orders.show',
            'destroy' => 'admin.orders.destroy',
        ];
    }

    public function getPermissions(): array
    {
        return [
            'view' => 'order.view',
            'delete' => 'order.delete',
        ];
    }

    public function getModelNameSingular(): string
    {
        return 'Order';
    }

    public function getModelNamePlural(): string
    {
        return 'Orders';
    }

    public function getSearchbarPlaceholder(): string
    {
        return __('Search orders by number, customer, phone...');
    }

    protected function getHeaders(): array
    {
        return [
            [
                'id' => 'order_number',
                'title' => __('Order #'),
                'sortable' => true,
                'searchable' => true,
                'sortBy' => 'order_number',
            ],
            [
                'id' => 'customer',
                'title' => __('Customer'),
                'sortable' => true,
                'sortBy' => 'customer_id',
                'renderContent' => 'renderCustomerColumn',
            ],
            [
                'id' => 'agent',
                'title' => __('Agent'),
                'sortable' => true,
                'sortBy' => 'agent_id',
                'renderContent' => 'renderAgentColumn',
            ],
            [
                'id' => 'items_count',
                'title' => __('Items'),
                'sortable' => false,
                'renderContent' => 'renderItemsCountColumn',
            ],
            [
                'id' => 'total',
                'title' => __('Total'),
                'sortable' => true,
                'sortBy' => 'total',
                'renderContent' => 'renderTotalColumn',
            ],
            [
                'id' => 'payment_status',
                'title' => __('Payment'),
                'sortable' => true,
                'sortBy' => 'payment_status',
                'renderContent' => 'renderPaymentStatusColumn',
            ],
            [
                'id' => 'status',
                'title' => __('Status'),
                'sortable' => true,
                'sortBy' => 'status',
                'renderContent' => 'renderStatusColumn',
            ],
            [
                'id' => 'created_at',
                'title' => __('Date'),
                'sortable' => true,
                'sortBy' => 'created_at',
            ],
            [
                'id' => 'actions',
                'title' => __('Actions'),
                'sortable' => false,
                'is_action' => true,
            ],
        ];
    }

    public function renderCustomerColumn($order): string
    {
        if (!$order->customer) {
            return '<span class="text-gray-400 text-sm">' . __('N/A') . '</span>';
        }

        return '
            <div class="flex flex-col">
                <span class="font-medium text-gray-900 dark:text-white">' . e($order->customer->name) . '</span>
                <span class="text-xs text-gray-500 dark:text-gray-400">' . e($order->customer->phone) . '</span>
            </div>
        ';
    }

    public function renderAgentColumn($order): string
    {
        if (!$order->agent) {
            return '<span class="text-gray-400 text-sm">' . __('N/A') . '</span>';
        }

        return '
            <div class="flex items-center gap-2">
                <div class="flex h-8 w-8 items-center justify-center rounded-full bg-blue-100 dark:bg-blue-900/30">
                    <span class="text-xs font-medium text-blue-600 dark:text-blue-400">' .
                        strtoupper(substr($order->agent->first_name, 0, 1) . substr($order->agent->last_name ?? '', 0, 1)) .
                    '</span>
                </div>
                <span class="text-sm text-gray-900 dark:text-white">' . e($order->agent->full_name) . '</span>
            </div>
        ';
    }

    public function renderItemsCountColumn($order): string
    {
        $count = $order->items->count();
        return '<span class="inline-flex items-center rounded-full bg-gray-100 px-2.5 py-0.5 text-xs font-medium text-gray-800 dark:bg-gray-700 dark:text-gray-300">' . $count . '</span>';
    }

    public function renderTotalColumn($order): string
    {
        return '<span class="font-medium text-gray-900 dark:text-white">$' . number_format((float) $order->total, 2) . '</span>';
    }

    public function renderPaymentStatusColumn($order): string
    {
        $colors = [
            'pending' => 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400',
            'processing' => 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400',
            'completed' => 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400',
            'failed' => 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400',
            'refunded' => 'bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-400',
        ];

        $color = $colors[$order->payment_status] ?? 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300';

        return '<span class="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ' . $color . '">' .
            ucfirst($order->payment_status) .
        '</span>';
    }

    public function renderStatusColumn($order): string
    {
        $colors = [
            'pending' => 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400',
            'processing' => 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400',
            'completed' => 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400',
            'cancelled' => 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400',
            'failed' => 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400',
        ];

        $color = $colors[$order->status] ?? 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300';

        return '<span class="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ' . $color . '">' .
            ucfirst($order->status) .
        '</span>';
    }

    public function renderActionsColumn($order): string
    {
        $html = '<div class="flex items-center space-x-2">';

        // View button
        if (auth()->user()->can('view', $order)) {
            $html .= '<a href="' . route('admin.orders.show', $order) . '" class="inline-flex items-center justify-center w-8 h-8 text-blue-600 bg-blue-50 border border-blue-200 rounded-lg hover:bg-blue-100 hover:text-blue-700 transition-colors duration-200" title="' . __('View Order') . '">';
            $html .= '<iconify-icon icon="lucide:eye" class="w-4 h-4"></iconify-icon>';
            $html .= '</a>';
        }

        // Delete button with confirmation modal (following system pattern)
        if (auth()->user()->can('delete', $order)) {
            $html .= '<div x-data="{ deleteModalOpen: false }">';
            $html .= '<button @click="deleteModalOpen = true" class="inline-flex items-center justify-center w-8 h-8 text-red-600 bg-red-50 border border-red-200 rounded-lg hover:bg-red-100 hover:text-red-700 transition-colors duration-200" title="' . __('Delete Order') . '">';
            $html .= '<iconify-icon icon="lucide:trash-2" class="w-4 h-4"></iconify-icon>';
            $html .= '</button>';

            // Confirmation modal
            $html .= '<div x-cloak x-show="deleteModalOpen" x-transition.opacity.duration.200ms x-trap.inert.noscroll="deleteModalOpen" x-on:keydown.esc.window="deleteModalOpen = false" x-on:click.self="deleteModalOpen = false" class="fixed inset-0 z-50 flex items-center justify-center bg-black/20 p-4 backdrop-blur-md" role="dialog" aria-modal="true">';
            $html .= '<div x-show="deleteModalOpen" x-transition:enter="transition ease-out duration-200 delay-100" x-transition:enter-start="opacity-0 scale-50" x-transition:enter-end="opacity-100 scale-100" class="w-full max-w-md rounded-lg bg-white p-0 shadow-xl dark:bg-gray-800">';

            // Modal header
            $html .= '<div class="flex items-center justify-between border-b border-gray-100 p-4 dark:border-gray-800">';
            $html .= '<h3 class="font-semibold tracking-wide text-gray-700 dark:text-white">' . __('Delete Order') . '</h3>';
            $html .= '<button x-on:click="deleteModalOpen = false" class="text-gray-400 hover:bg-gray-200 hover:text-gray-700 rounded-md p-1 dark:hover:bg-gray-600 dark:hover:text-white"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke="currentColor" fill="none" stroke-width="1.4" class="w-5 h-5"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/></svg></button>';
            $html .= '</div>';

            // Modal body
            $html .= '<div class="px-4 py-6 text-center">';
            $html .= '<p class="text-gray-500 dark:text-gray-300">' . __('Are you sure you want to delete this order?') . '</p>';
            $html .= '<p class="font-medium text-gray-900 dark:text-white mt-2">' . e($order->order_number) . '</p>';
            $html .= '<p class="text-sm text-gray-400 mt-1">' . __('This action cannot be undone.') . '</p>';
            $html .= '</div>';

            // Modal footer
            $html .= '<div class="flex items-center justify-end gap-3 border-t border-gray-100 p-4 dark:border-gray-800">';
            $html .= '<button type="button" x-on:click="deleteModalOpen = false" class="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:text-white dark:focus:ring-gray-700">' . __('No, Cancel') . '</button>';
            $html .= '<button type="button" wire:click="deleteItem(' . $order->id . ')" @click="deleteModalOpen = false" class="px-4 py-2 text-sm font-medium text-white bg-red-600 rounded-md hover:bg-red-800 focus:outline-none focus:ring-2 focus:ring-red-300 dark:focus:ring-red-800">' . __('Yes, Delete') . '</button>';
            $html .= '</div>';

            $html .= '</div>';
            $html .= '</div>';
            $html .= '</div>';
        }

        $html .= '</div>';

        return $html;
    }

    public function executeBulkAction(string $action): void
    {
        $selectedIds = $this->getSelectedIds();

        if (empty($selectedIds)) {
            $this->dispatch('show-toast', [
                'message' => __('Please select items first'),
                'type' => 'warning',
            ]);
            return;
        }

        match ($action) {
            'mark_processing' => $this->bulkUpdateStatusTo('processing'),
            'mark_completed' => $this->bulkUpdateStatusTo('completed'),
            'mark_cancelled' => $this->bulkUpdateStatusTo('cancelled'),
            'delete' => $this->bulkDelete(),
            default => null,
        };
    }

    protected function bulkUpdateStatusTo(string $status): void
    {
        $ids = $this->selectedItems;

        if (empty($ids)) {
            return;
        }

        Order::whereIn('id', $ids)->update(['status' => $status]);

        $this->dispatch('show-toast', [
            'message' => __(':count orders updated successfully', ['count' => count($ids)]),
            'type' => 'success',
        ]);

        $this->selectedItems = [];
        $this->dispatch('resetSelectedItems');
    }

    public function bulkDelete(): void
    {
        $ids = $this->selectedItems;

        if (empty($ids)) {
            $this->dispatch('show-toast', [
                'message' => __('No orders selected'),
                'type' => 'warning',
            ]);
            return;
        }

        Order::whereIn('id', $ids)->delete();

        $this->dispatch('show-toast', [
            'message' => __(':count orders deleted successfully', ['count' => count($ids)]),
            'type' => 'success',
        ]);

        $this->selectedItems = [];
        $this->dispatch('resetSelectedItems');
    }
}
