<?php

declare(strict_types=1);

namespace App\Livewire\Datatable;

use App\Models\PaymentTransaction;
use Illuminate\Database\Eloquent\Builder;

class PaymentTransactionDatatable extends Datatable
{
    public string $model = PaymentTransaction::class;

    public bool $showFilters = true;
    public array $relationships = ['customer', 'order'];
    public array $autoGeneratedHeaders = [];

    public array $searchableColumns = ['transaction_id', 'reference_id', 'customer_phone', 'customer_name'];

    public array $filterableColumns = [
        'status' => [
            'pending' => 'Pending',
            'processing' => 'Processing',
            'completed' => 'Completed',
            'failed' => 'Failed',
            'expired' => 'Expired',
            'cancelled' => 'Cancelled',
        ],
        'payment_method' => [
            'MWALLET_ACCOUNT' => 'Mobile Wallet',
        ],
        'provider' => [
            'EVC PLUS' => 'EVC PLUS',
            'ZAAD' => 'ZAAD',
            'JEEB' => 'JEEB',
            'SAHAL' => 'SAHAL',
        ],
    ];

    public array $sortableColumns = [
        'reference_id',
        'amount',
        'status',
        'created_at',
    ];

    public function query(): Builder
    {
        return PaymentTransaction::query()
            ->with(['customer', 'order'])
            ->when($this->search, function (Builder $query) {
                $query->where(function (Builder $q) {
                    $q->where('reference_id', 'like', '%' . $this->search . '%')
                        ->orWhere('transaction_id', 'like', '%' . $this->search . '%')
                        ->orWhere('customer_phone', 'like', '%' . $this->search . '%')
                        ->orWhere('customer_name', 'like', '%' . $this->search . '%');
                });
            })
            ->when($this->filters['status'] ?? null, function (Builder $query, $status) {
                $query->where('status', $status);
            })
            ->when($this->filters['payment_method'] ?? null, function (Builder $query, $paymentMethod) {
                $query->where('payment_method', $paymentMethod);
            })
            ->when($this->filters['provider'] ?? null, function (Builder $query, $provider) {
                $query->where('provider', $provider);
            })
            ->orderBy($this->sort, $this->direction);
    }

    public function getRoutes(): array
    {
        return [
            'index' => 'admin.transactions.index',
            'show' => 'admin.transactions.show',
        ];
    }

    public function getPermissions(): array
    {
        return [
            'view' => 'transaction.view',
        ];
    }

    public function getModelNameSingular(): string
    {
        return 'Transaction';
    }

    public function getModelNamePlural(): string
    {
        return 'Transactions';
    }

    public function getSearchbarPlaceholder(): string
    {
        return __('Search transactions by reference, customer...');
    }

    protected function getHeaders(): array
    {
        return [
            [
                'id' => 'reference_id',
                'title' => __('Reference ID'),
                'sortable' => true,
                'sortBy' => 'reference_id',
                'renderContent' => 'renderReferenceColumn',
            ],
            [
                'id' => 'customer',
                'title' => __('Customer'),
                'sortable' => false,
                'renderContent' => 'renderCustomerColumn',
            ],
            [
                'id' => 'amount',
                'title' => __('Amount'),
                'sortable' => true,
                'sortBy' => 'amount',
                'renderContent' => 'renderAmountColumn',
            ],
            [
                'id' => 'provider',
                'title' => __('Provider'),
                'sortable' => false,
                'renderContent' => 'renderProviderColumn',
            ],
            [
                'id' => 'status',
                'title' => __('Status'),
                'sortable' => true,
                'sortBy' => 'status',
                'renderContent' => 'renderStatusColumn',
            ],
            [
                'id' => 'order',
                'title' => __('Order'),
                'sortable' => false,
                'renderContent' => 'renderOrderColumn',
            ],
            [
                'id' => 'created_at',
                'title' => __('Date'),
                'sortable' => true,
                'sortBy' => 'created_at',
            ],
            [
                'id' => 'actions',
                'title' => __('Actions'),
                'sortable' => false,
                'is_action' => true,
            ],
        ];
    }

    public function renderReferenceColumn($transaction): string
    {
        return '
            <div class="flex flex-col">
                <span class="font-medium text-gray-900 dark:text-white">' . e($transaction->reference_id) . '</span>
                ' . ($transaction->transaction_id ? '<span class="text-xs text-gray-500 dark:text-gray-400">' . e($transaction->transaction_id) . '</span>' : '') . '
            </div>
        ';
    }

    public function renderCustomerColumn($transaction): string
    {
        if (!$transaction->customer_name) {
            return '<span class="text-gray-400 text-sm">' . __('N/A') . '</span>';
        }

        return '
            <div class="flex flex-col">
                <span class="font-medium text-gray-900 dark:text-white">' . e($transaction->customer_name) . '</span>
                <span class="text-xs text-gray-500 dark:text-gray-400">' . e($transaction->customer_phone) . '</span>
            </div>
        ';
    }

    public function renderAmountColumn($transaction): string
    {
        return '<span class="font-medium text-gray-900 dark:text-white">' . e($transaction->currency) . ' ' . number_format((float) $transaction->amount, 2) . '</span>';
    }

    public function renderProviderColumn($transaction): string
    {
        if (!$transaction->provider) {
            return '<span class="text-gray-400 text-sm">' . __('N/A') . '</span>';
        }

        // Enhanced provider badges with icons and better styling
        $providers = [
            'EVC PLUS' => [
                'color' => 'bg-blue-50 text-blue-700 border border-blue-200 dark:bg-blue-900/20 dark:text-blue-400 dark:border-blue-800',
                'icon' => 'lucide:smartphone',
            ],
            'ZAAD' => [
                'color' => 'bg-green-50 text-green-700 border border-green-200 dark:bg-green-900/20 dark:text-green-400 dark:border-green-800',
                'icon' => 'lucide:wallet',
            ],
            'JEEB' => [
                'color' => 'bg-purple-50 text-purple-700 border border-purple-200 dark:bg-purple-900/20 dark:text-purple-400 dark:border-purple-800',
                'icon' => 'lucide:credit-card',
            ],
            'SAHAL' => [
                'color' => 'bg-orange-50 text-orange-700 border border-orange-200 dark:bg-orange-900/20 dark:text-orange-400 dark:border-orange-800',
                'icon' => 'lucide:banknote',
            ],
        ];

        $provider = $providers[$transaction->provider] ?? [
            'color' => 'bg-gray-50 text-gray-700 border border-gray-200 dark:bg-gray-900/20 dark:text-gray-400 dark:border-gray-800',
            'icon' => 'lucide:help-circle',
        ];

        return '<span class="inline-flex items-center rounded-md px-2.5 py-1 text-xs font-semibold ' . $provider['color'] . '">
            ' . e($transaction->provider) . '
        </span>';
    }

    public function renderStatusColumn($transaction): string
    {
        // Enhanced status badges with icons and better styling
        $statuses = [
            'completed' => [
                'color' => 'bg-green-50 text-green-700 border border-green-200 dark:bg-green-900/20 dark:text-green-400 dark:border-green-800',
                'icon' => 'lucide:check-circle',
            ],
            'pending' => [
                'color' => 'bg-yellow-50 text-yellow-700 border border-yellow-200 dark:bg-yellow-900/20 dark:text-yellow-400 dark:border-yellow-800',
                'icon' => 'lucide:clock',
            ],
            'processing' => [
                'color' => 'bg-blue-50 text-blue-700 border border-blue-200 dark:bg-blue-900/20 dark:text-blue-400 dark:border-blue-800',
                'icon' => 'lucide:loader',
            ],
            'failed' => [
                'color' => 'bg-red-50 text-red-700 border border-red-200 dark:bg-red-900/20 dark:text-red-400 dark:border-red-800',
                'icon' => 'lucide:x-circle',
            ],
            'expired' => [
                'color' => 'bg-gray-50 text-gray-700 border border-gray-200 dark:bg-gray-900/20 dark:text-gray-400 dark:border-gray-800',
                'icon' => 'lucide:clock-off',
            ],
            'cancelled' => [
                'color' => 'bg-gray-50 text-gray-700 border border-gray-200 dark:bg-gray-900/20 dark:text-gray-400 dark:border-gray-800',
                'icon' => 'lucide:ban',
            ],
        ];

        $status = $statuses[$transaction->status] ?? [
            'color' => 'bg-gray-50 text-gray-700 border border-gray-200 dark:bg-gray-900/20 dark:text-gray-400 dark:border-gray-800',
            'icon' => 'lucide:help-circle',
        ];

        return '<span class="inline-flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs font-semibold ' . $status['color'] . '">
            <iconify-icon icon="' . $status['icon'] . '" class="h-3.5 w-3.5"></iconify-icon>
            ' . ucfirst($transaction->status) . '
        </span>';
    }

    public function renderOrderColumn($transaction): string
    {
        if (!$transaction->order) {
            return '<span class="text-gray-400 text-sm">' . __('No Order') . '</span>';
        }

        return '<a href="' . route('admin.orders.show', $transaction->order) . '" class="text-primary hover:underline font-medium">' . e($transaction->order->order_number) . '</a>';
    }

    public function renderDateColumn($transaction): string
    {
        return '
            <div class="flex flex-col">
                <span class="text-sm text-gray-900 dark:text-white">' . $transaction->created_at->format('M d, Y') . '</span>
                <span class="text-xs text-gray-500 dark:text-gray-400">' . $transaction->created_at->format('h:i A') . '</span>
            </div>
        ';
    }

    public function renderActionsColumn($transaction): string
    {
        return '
            <div class="flex items-center gap-2">
                <a href="' . route('admin.transactions.show', $transaction) . '" class="text-primary hover:text-primary-dark">
                    <iconify-icon icon="lucide:eye" class="h-4 w-4"></iconify-icon>
                </a>
            </div>
        ';
    }

    public function bulkDelete(): void
    {
        $this->authorize('transaction.delete');

        $ids = $this->selectedItems;

        if (empty($ids)) {
            $this->dispatch('show-toast', [
                'message' => __('No transactions selected'),
                'type' => 'warning',
            ]);
            return;
        }

        try {
            $deletedCount = PaymentTransaction::whereIn('id', $ids)->delete();

            if ($deletedCount === 0) {
                $this->dispatch('show-toast', [
                    'message' => __('No transactions were deleted. Selected items may include protected records.'),
                    'type' => 'error',
                ]);
            } else {
                $this->dispatch('show-toast', [
                    'message' => __(':count transactions deleted successfully', ['count' => $deletedCount]),
                    'type' => 'success',
                ]);
            }
        } catch (\Exception $e) {
            $this->dispatch('show-toast', [
                'message' => __('Failed to delete transactions: :error', ['error' => $e->getMessage()]),
                'type' => 'error',
            ]);
        }

        // Reset selected items
        $this->selectedItems = [];
        $this->dispatch('resetSelectedItems');
    }

}

