<?php

declare(strict_types=1);

namespace App\Livewire\Datatable;

use App\Models\PaymentTransaction;
use Illuminate\Database\Eloquent\Builder;

class PaymentTransactionDatatable extends Datatable
{
    public string $model = PaymentTransaction::class;

    public bool $showFilters = true;
    public array $relationships = ['customer', 'order'];
    public array $autoGeneratedHeaders = [];

    public array $searchableColumns = ['transaction_id', 'reference_id', 'customer_phone', 'customer_name'];

    public array $filterableColumns = [
        'status' => [
            'pending' => 'Pending',
            'processing' => 'Processing',
            'completed' => 'Completed',
            'failed' => 'Failed',
            'expired' => 'Expired',
            'cancelled' => 'Cancelled',
        ],
        'payment_method' => [
            'MWALLET_ACCOUNT' => 'Mobile Wallet',
        ],
        'provider' => [
            'EVC PLUS' => 'EVC PLUS',
            'ZAAD' => 'ZAAD',
            'JEEB' => 'JEEB',
            'SAHAL' => 'SAHAL',
        ],
    ];

    public array $sortableColumns = [
        'reference_id',
        'amount',
        'status',
        'created_at',
    ];

    public function query(): Builder
    {
        return PaymentTransaction::query()
            ->with(['customer', 'order'])
            ->when($this->search, function (Builder $query) {
                $query->where(function (Builder $q) {
                    $q->where('reference_id', 'like', '%' . $this->search . '%')
                        ->orWhere('transaction_id', 'like', '%' . $this->search . '%')
                        ->orWhere('customer_phone', 'like', '%' . $this->search . '%')
                        ->orWhere('customer_name', 'like', '%' . $this->search . '%');
                });
            })
            ->when($this->filters['status'] ?? null, function (Builder $query, $status) {
                $query->where('status', $status);
            })
            ->when($this->filters['payment_method'] ?? null, function (Builder $query, $paymentMethod) {
                $query->where('payment_method', $paymentMethod);
            })
            ->when($this->filters['provider'] ?? null, function (Builder $query, $provider) {
                $query->where('provider', $provider);
            })
            ->orderBy($this->sort, $this->direction);
    }

    public function getRoutes(): array
    {
        return [
            'index' => 'admin.transactions.index',
            'show' => 'admin.transactions.show',
        ];
    }

    public function getPermissions(): array
    {
        return [
            'view' => 'transaction.view',
        ];
    }

    public function getModelNameSingular(): string
    {
        return 'Transaction';
    }

    public function getModelNamePlural(): string
    {
        return 'Transactions';
    }

    public function getSearchbarPlaceholder(): string
    {
        return __('Search transactions by reference, customer...');
    }

    protected function getHeaders(): array
    {
        return [
            [
                'id' => 'reference_id',
                'title' => __('Reference ID'),
                'sortable' => true,
                'sortBy' => 'reference_id',
                'renderContent' => 'renderReferenceColumn',
            ],
            [
                'id' => 'customer',
                'title' => __('Customer'),
                'sortable' => false,
                'renderContent' => 'renderCustomerColumn',
            ],
            [
                'id' => 'amount',
                'title' => __('Amount'),
                'sortable' => true,
                'sortBy' => 'amount',
                'renderContent' => 'renderAmountColumn',
            ],
            [
                'id' => 'provider',
                'title' => __('Provider'),
                'sortable' => false,
                'renderContent' => 'renderProviderColumn',
            ],
            [
                'id' => 'status',
                'title' => __('Status'),
                'sortable' => true,
                'sortBy' => 'status',
                'renderContent' => 'renderStatusColumn',
            ],
            [
                'id' => 'order',
                'title' => __('Order'),
                'sortable' => false,
                'renderContent' => 'renderOrderColumn',
            ],
            [
                'id' => 'created_at',
                'title' => __('Date'),
                'sortable' => true,
                'sortBy' => 'created_at',
            ],
            [
                'id' => 'actions',
                'title' => __('Actions'),
                'sortable' => false,
                'is_action' => true,
            ],
        ];
    }

    public function renderReferenceColumn($transaction): string
    {
        return '
            <div class="flex flex-col">
                <span class="font-medium text-gray-900 dark:text-white">' . e($transaction->reference_id) . '</span>
                ' . ($transaction->transaction_id ? '<span class="text-xs text-gray-500 dark:text-gray-400">' . e($transaction->transaction_id) . '</span>' : '') . '
            </div>
        ';
    }

    public function renderCustomerColumn($transaction): string
    {
        if (!$transaction->customer_name) {
            return '<span class="text-gray-400 text-sm">' . __('N/A') . '</span>';
        }

        return '
            <div class="flex flex-col">
                <span class="font-medium text-gray-900 dark:text-white">' . e($transaction->customer_name) . '</span>
                <span class="text-xs text-gray-500 dark:text-gray-400">' . e($transaction->customer_phone) . '</span>
            </div>
        ';
    }

    public function renderAmountColumn($transaction): string
    {
        return '<span class="font-medium text-gray-900 dark:text-white">' . e($transaction->currency) . ' ' . number_format((float) $transaction->amount, 2) . '</span>';
    }

    public function renderProviderColumn($transaction): string
    {
        if (!$transaction->provider) {
            return '<span class="text-gray-400 text-sm">' . __('N/A') . '</span>';
        }

        $colors = [
            'EVC PLUS' => 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300',
            'ZAAD' => 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300',
            'JEEB' => 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-300',
            'SAHAL' => 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-300',
        ];

        $color = $colors[$transaction->provider] ?? 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-300';

        return '<span class="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ' . $color . '">' . e($transaction->provider) . '</span>';
    }

    public function renderStatusColumn($transaction): string
    {
        $colors = [
            'completed' => 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300',
            'pending' => 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-300',
            'processing' => 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300',
            'failed' => 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300',
            'expired' => 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-300',
            'cancelled' => 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-300',
        ];

        $color = $colors[$transaction->status] ?? 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-300';

        return '<span class="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ' . $color . '">' . ucfirst($transaction->status) . '</span>';
    }

    public function renderOrderColumn($transaction): string
    {
        if (!$transaction->order) {
            return '<span class="text-gray-400 text-sm">' . __('No Order') . '</span>';
        }

        return '<a href="' . route('admin.orders.show', $transaction->order) . '" class="text-primary hover:underline font-medium">' . e($transaction->order->order_number) . '</a>';
    }

    public function renderDateColumn($transaction): string
    {
        return '
            <div class="flex flex-col">
                <span class="text-sm text-gray-900 dark:text-white">' . $transaction->created_at->format('M d, Y') . '</span>
                <span class="text-xs text-gray-500 dark:text-gray-400">' . $transaction->created_at->format('h:i A') . '</span>
            </div>
        ';
    }

    public function renderActionsColumn($transaction): string
    {
        return '
            <div class="flex items-center gap-2">
                <a href="' . route('admin.transactions.show', $transaction) . '" class="text-primary hover:text-primary-dark">
                    <iconify-icon icon="lucide:eye" class="h-4 w-4"></iconify-icon>
                </a>
            </div>
        ';
    }

}

