<x-datatable
    :searchbarPlaceholder="$searchbarPlaceholder"
    :filters="$filters"
    :customFilters="$customFilters"
    :perPageOptions="$perPageOptions"
    :headers="$headers"
    :enableCheckbox="$enableCheckbox"
    :noResultsMessage="$noResultsMessage"
    :customNoResultsMessage="$customNoResultsMessage"
    :data="$data"
    :newResourceLinkPermission="$newResourceLinkPermission"
    :newResourceLinkRouteName="$newResourceLinkRouteName"
    :newResourceLinkRouteUrl="$this->getCreateRouteUrl()"
    :newResourceLinkLabel="$newResourceLinkLabel"
    :pdfRoute="$pdfRoute ?? null"
    :exportRoute="$exportRoute ?? null"
    :importRoute="$importRoute ?? null"
    :enablePdf="$enablePdf ?? true"
    :enablePrint="$enablePrint ?? true"
    :enableExport="$enableExport ?? false"
    :enableImport="$enableImport ?? false"
/>
